# This is a basic workflow to help you get started with Actions

name: 'Hello World'
description: 'Greet someone'


inputs: 
  hello_world_var:
    description: read from the caller
    required: true

runs:
  using: "composite"
  steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run goodbye.sh
      shell: bash
      run: print.sh "${{ inputs.hello_world_var }}"
