name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
      enviro:
        required: true
        type: string
     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Convert enviro to boolean
        id: convert-enviro
        run: |
          if [ "${{ inputs.enviro }}" = "prod" ]; then
            echo "isProd=true" >> $GITHUB_ENV
          else
            echo "isProd=false" >> $GITHUB_ENV
          fi
          
      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.node }}  ${{ inputs.enviro }}"
          env
          echo "Enviro is set to: ${{ env.isProd }}"
           
      - name: ReusableAction
        uses: dcharan/reusable_actions/.github/custom_reusable_actions@main
        with:
          action_input: 'Mona the Octocat'
           
