name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
      enviro:
        required: true
        type: string
     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Convert enviro to boolean
        id: convert-enviro
        run: |
          if [[ "${{ inputs.enviro }}" = "prod" || "${{ inputs.enviro }}" = "prd" ]]; then
            echo "isProd=true" >> $GITHUB_ENV
            echo "isProdSt='true'" >> $GITHUB_ENV
          else
            echo "isProd=false" >> $GITHUB_ENV
            echo "isProdSt='false'" >> $GITHUB_ENV
          fi
          
      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.node }}  ${{ inputs.enviro }}"
          echo ${{ env.isProd }}
          echo ${{ env.isProdSt }}
          
          if ${{ env.isProd }}; then
            echo "yes its isProd"
          fi

          if ${{ env.isProdSt }}; then
            echo "yes its isProdSt"
          fi
           
      - name: ReusableAction
        uses: dcharan/reusable_actions/.github/custom_reusable_actions@main
        with:
          action_input: 'Mona the Octocat'
           
